# Generated by Django 3.0.3 on 2020-02-27 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dormroom", "0002_auto_20200227_2157"),
        ("Washlist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateWashList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=250)),
            ],
            options={"verbose_name": "Mal for vaskeliste"},
        ),
        migrations.RemoveField(model_name="listitem", name="list_name"),
        migrations.AddField(
            model_name="listitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listitem",
            name="desc",
            field=models.CharField(
                blank=True, help_text="Hva skal vaskes?", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="Washlist",
            name="dormroom",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Dormroom.Dormroom",
            ),
        ),
        migrations.AddField(
            model_name="Washlist",
            name="title",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.CreateModel(
            name="TemplateListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="", help_text="Hva skal vaskes?", max_length=150
                    ),
                ),
                (
                    "Washlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Washlist.TemplateWashList",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listitem",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Washlist.TemplateListItem",
            ),
        ),
    ]
