# Generated by Django 3.0.3 on 2020-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("washlist", "0002_auto_20200227_2219")]

    operations = [
        migrations.AddConstraint(
            model_name="listitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("template_id__isnull", True),
                    ("desc__isnull", True),
                    _connector="OR",
                ),
                name="Must have description",
            ),
        )
    ]
