# Generated by Django 3.0.3 on 2020-02-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Washlist", "0003_auto_20200227_2222")]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="based_items",
                to="Washlist.TemplateListItem",
            ),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="Washlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Washlist.WashList",
            ),
        ),
    ]
