# Generated by Django 3.0.3 on 2020-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("washlist", "0004_auto_20200229_1420")]

    operations = [
        migrations.RemoveConstraint(
            model_name="listitem", name="Must have description"
        ),
        migrations.AlterField(
            model_name="templatelistitem",
            name="description",
            field=models.CharField(help_text="Hva skal vaskes?", max_length=150),
        ),
        migrations.AddConstraint(
            model_name="listitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("template_id__isnull", False),
                    ("desc__isnull", False),
                    _connector="OR",
                ),
                name="Must have description from either template or self",
            ),
        ),
    ]
