# Generated by Django 3.0.5 on 2020-04-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("Washlist", "0007_auto_20200309_1422")]

    operations = [
        migrations.RenameField(
            model_name="templatelistitem", old_name="Washlist", new_name="washlist"
        )
    ]
