cache:
  key: one-key-to-rule-them-all
  paths:
    - .cache/pip
    - venv/

.before_script_template:
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - cd backend
    - pip install poetry
    - poetry install

lint-python:
  image: python:3.8
  extends: .before_script_template
  script:
    - isort -rc -c .
    - black --check .

check-missing-migrations:
  image: python:3.8
  extends: .before_script_template
  script:
    - python manage.py makemigrations --check

lint-typescript:
  image: node:12
  script:
    - cd frontend
    - npm ci
    - node_modules/eslint/bin/eslint.js --ext .tsx,.ts .

test-backend:
  image: python:3.8
  extends: .before_script_template
  script:
    - coverage run ./manage.py test
    - coverage report

test-frontend:
  image: node:12
  script:
    - cd frontend
    - npm ci
    - npm test
    

variables:
  POETRY_VIRTUALENVS_CREATE: "false"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
