cache:
  paths:
    - ~/.cache/pip/

lint-python:
  image: python:3.8
  script:
    - cd sif_vaskelister
    - pip install poetry
    - poetry install
    - isort -rc -c .
    - black --check .

lint-typescript:
  image: node:12
  script:
    - cd frontend/sif_vaskelister
    - npm ci
    - node_modules/eslint/bin/eslint.js --ext .tsx,.ts .

test:
  image: python:3.8
  script:
    - cd sif_vaskelister
    - pip install poetry
    - poetry install
    - coverage run ./manage.py test
    - coverage report

variables:
  POETRY_VIRTUALENVS_CREATE: "false"
