# Generated by Django 3.0.3 on 2020-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("Dormroom", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="dormroom",
            options={"verbose_name": "Kollektiv", "verbose_name_plural": "Kollektiver"},
        )
    ]
