# Generated by Django 3.0.3 on 2020-02-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("SIFUser", "0003_auto_20200221_1058")]

    operations = [
        migrations.RenameField(model_name="user", old_name="dorm", new_name="dormroom")
    ]
