# Generated by Django 3.0.3 on 2020-03-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washlist', '0006_auto_20200305_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelistitem',
            name='washlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='washlist.TemplateWashList'),
        ),
    ]
