# Generated by Django 3.0.3 on 2020-02-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("Dormroom", "0001_initial"), ("SIFUser", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dorm",
            field=models.ForeignKey(
                blank=True,
                help_text="Kollektivet personen bor i",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dormroom.Dormroom",
            ),
        )
    ]
