# Generated by Django 3.0.3 on 2020-02-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("SIFUser", "0002_user_dorm")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Bruker", "verbose_name_plural": "Brukere"},
        )
    ]
