# Generated by Django 3.0.3 on 2020-02-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SIFUser", "0003_auto_20200227_2157"),
        ("SIFUser", "0004_auto_20200224_1152"),
    ]

    operations = []
