# Generated by Django 3.0.3 on 2020-02-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dormroom", "0002_auto_20200227_2157"),
        ("Dormroom", "0002_auto_20200221_1058"),
    ]

    operations = []
