# Generated by Django 3.0.3 on 2020-02-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("StudentVillage", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="studentvillage",
            options={"verbose_name": "Studentby", "verbose_name_plural": "Studentbyer"},
        ),
        migrations.AddField(
            model_name="studentvillage",
            name="name",
            field=models.CharField(
                default="", help_text="Navn på studentby", max_length=80
            ),
        ),
    ]
