# Generated by Django 3.0.3 on 2020-02-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StudentVillage", "0003_studentvillage_templatewashlist"),
        ("StudentVillage", "0004_auto_20200224_1401"),
    ]

    operations = []
